[versions]

# Global
kotlin = "2.2.10"

# Plugins
kotlin-dsl-plugin = "6.2.0"
android-plugin = "8.12.2"
compose-plugin = "1.8.2"
ktlint-plugin = "13.1.0"

# Libraries
kotlinx-datetime = "0.7.1"

compose-activity = "1.10.1"
compose-tooling = "1.9.0"

[plugins]
kotlin-dsl = { id = "org.gradle.kotlin.kotlin-dsl", version.ref = "kotlin-dsl-plugin" }
android = { id = "com.android.application", version.ref = "android-plugin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ktlint = {id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-plugin"}

[libraries]
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose-activity" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-tooling" }
